// List of US Colleges and Universities
// This is a comprehensive list - you may want to load this from your database instead

export const US_SCHOOLS = [
  { value: 'harvard', label: 'Harvard University' },
  { value: 'stanford', label: 'Stanford University' },
  { value: 'mit', label: 'Massachusetts Institute of Technology (MIT)' },
  { value: 'yale', label: 'Yale University' },
  { value: 'princeton', label: 'Princeton University' },
  { value: 'columbia', label: 'Columbia University' },
  { value: 'uchicago', label: 'University of Chicago' },
  { value: 'caltech', label: 'California Institute of Technology' },
  { value: 'upenn', label: 'University of Pennsylvania' },
  { value: 'duke', label: 'Duke University' },
  { value: 'northwestern', label: 'Northwestern University' },
  { value: 'dartmouth', label: 'Dartmouth College' },
  { value: 'brown', label: 'Brown University' },
  { value: 'vanderbilt', label: 'Vanderbilt University' },
  { value: 'rice', label: 'Rice University' },
  { value: 'wustl', label: 'Washington University in St. Louis' },
  { value: 'cornell', label: 'Cornell University' },
  { value: 'notre-dame', label: 'University of Notre Dame' },
  { value: 'ucla', label: 'University of California, Los Angeles (UCLA)' },
  { value: 'berkeley', label: 'University of California, Berkeley' },
  { value: 'umich', label: 'University of Michigan' },
  { value: 'uva', label: 'University of Virginia' },
  { value: 'unc', label: 'University of North Carolina at Chapel Hill' },
  { value: 'usc', label: 'University of Southern California' },
  { value: 'georgia-tech', label: 'Georgia Institute of Technology' },
  { value: 'nyu', label: 'New York University' },
  { value: 'tufts', label: 'Tufts University' },
  { value: 'ucsd', label: 'University of California, San Diego' },
  { value: 'ucsb', label: 'University of California, Santa Barbara' },
  { value: 'ucdavis', label: 'University of California, Davis' },
  { value: 'uci', label: 'University of California, Irvine' },
  { value: 'ucsc', label: 'University of California, Santa Cruz' },
  { value: 'ucr', label: 'University of California, Riverside' },
  { value: 'ucm', label: 'University of California, Merced' },
  { value: 'uconn', label: 'University of Connecticut' },
  { value: 'uri', label: 'University of Rhode Island' },
  { value: 'umass-amherst', label: 'University of Massachusetts Amherst' },
  { value: 'umass-boston', label: 'University of Massachusetts Boston' },
  { value: 'umass-dartmouth', label: 'University of Massachusetts Dartmouth' },
  { value: 'umass-lowell', label: 'University of Massachusetts Lowell' },
  { value: 'boston-university', label: 'Boston University' },
  { value: 'boston-college', label: 'Boston College' },
  { value: 'northeastern', label: 'Northeastern University' },
  { value: 'brandeis', label: 'Brandeis University' },
  { value: 'williams', label: 'Williams College' },
  { value: 'amherst', label: 'Amherst College' },
  { value: 'wellesley', label: 'Wellesley College' },
  { value: 'middlebury', label: 'Middlebury College' },
  { value: 'bowdoin', label: 'Bowdoin College' },
  { value: 'swarthmore', label: 'Swarthmore College' },
  { value: 'pomona', label: 'Pomona College' },
  { value: 'claremont', label: 'Claremont McKenna College' },
  { value: 'harvey-mudd', label: 'Harvey Mudd College' },
  { value: 'pitzer', label: 'Pitzer College' },
  { value: 'scripps', label: 'Scripps College' },
  { value: 'carleton', label: 'Carleton College' },
  { value: 'grinnell', label: 'Grinnell College' },
  { value: 'davidson', label: 'Davidson College' },
  { value: 'wake-forest', label: 'Wake Forest University' },
  { value: 'emory', label: 'Emory University' },
  { value: 'georgetown', label: 'Georgetown University' },
  { value: 'george-washington', label: 'George Washington University' },
  { value: 'american', label: 'American University' },
  { value: 'howard', label: 'Howard University' },
  { value: 'jhu', label: 'Johns Hopkins University' },
  { value: 'umd', label: 'University of Maryland' },
  { value: 'rutgers', label: 'Rutgers University' },
  { value: 'penn-state', label: 'Pennsylvania State University' },
  { value: 'pitt', label: 'University of Pittsburgh' },
  { value: 'cmu', label: 'Carnegie Mellon University' },
  { value: 'lehigh', label: 'Lehigh University' },
  { value: 'villanova', label: 'Villanova University' },
  { value: 'temple', label: 'Temple University' },
  { value: 'drexel', label: 'Drexel University' },
  { value: 'ohio-state', label: 'Ohio State University' },
  { value: 'miami-ohio', label: 'Miami University' },
  { value: 'case-western', label: 'Case Western Reserve University' },
  { value: 'oberlin', label: 'Oberlin College' },
  { value: 'kenyon', label: 'Kenyon College' },
  { value: 'wooster', label: 'College of Wooster' },
  { value: 'indiana', label: 'Indiana University' },
  { value: 'purdue', label: 'Purdue University' },
  { value: 'notre-dame-indiana', label: 'University of Notre Dame' },
  { value: 'illinois', label: 'University of Illinois' },
  { value: 'uiuc', label: 'University of Illinois Urbana-Champaign' },
  { value: 'northwestern-il', label: 'Northwestern University' },
  { value: 'uchicago-il', label: 'University of Chicago' },
  { value: 'wisconsin', label: 'University of Wisconsin' },
  { value: 'minnesota', label: 'University of Minnesota' },
  { value: 'iowa', label: 'University of Iowa' },
  { value: 'iowa-state', label: 'Iowa State University' },
  { value: 'missouri', label: 'University of Missouri' },
  { value: 'washington-st-louis', label: 'Washington University in St. Louis' },
  { value: 'texas', label: 'University of Texas' },
  { value: 'texas-am', label: 'Texas A&M University' },
  { value: 'rice-tx', label: 'Rice University' },
  { value: 'baylor', label: 'Baylor University' },
  { value: 'smu', label: 'Southern Methodist University' },
  { value: 'tcu', label: 'Texas Christian University' },
  { value: 'ut-austin', label: 'University of Texas at Austin' },
  { value: 'ut-dallas', label: 'University of Texas at Dallas' },
  { value: 'ut-arlington', label: 'University of Texas at Arlington' },
  { value: 'texas-tech', label: 'Texas Tech University' },
  { value: 'houston', label: 'University of Houston' },
  { value: 'arizona', label: 'University of Arizona' },
  { value: 'asu', label: 'Arizona State University' },
  { value: 'colorado', label: 'University of Colorado' },
  { value: 'colorado-state', label: 'Colorado State University' },
  { value: 'denver', label: 'University of Denver' },
  { value: 'utah', label: 'University of Utah' },
  { value: 'byu', label: 'Brigham Young University' },
  { value: 'nevada', label: 'University of Nevada' },
  { value: 'unlv', label: 'University of Nevada, Las Vegas' },
  { value: 'oregon', label: 'University of Oregon' },
  { value: 'oregon-state', label: 'Oregon State University' },
  { value: 'portland', label: 'University of Portland' },
  { value: 'washington', label: 'University of Washington' },
  { value: 'washington-state', label: 'Washington State University' },
  { value: 'gonzaga', label: 'Gonzaga University' },
  { value: 'alaska', label: 'University of Alaska' },
  { value: 'hawaii', label: 'University of Hawaii' },
  { value: 'florida', label: 'University of Florida' },
  { value: 'florida-state', label: 'Florida State University' },
  { value: 'miami', label: 'University of Miami' },
  { value: 'ucf', label: 'University of Central Florida' },
  { value: 'usf', label: 'University of South Florida' },
  { value: 'fiu', label: 'Florida International University' },
  { value: 'georgia', label: 'University of Georgia' },
  { value: 'georgia-tech-ga', label: 'Georgia Institute of Technology' },
  { value: 'emory-ga', label: 'Emory University' },
  { value: 'clemson', label: 'Clemson University' },
  { value: 'south-carolina', label: 'University of South Carolina' },
  { value: 'charleston', label: 'College of Charleston' },
  { value: 'alabama', label: 'University of Alabama' },
  { value: 'auburn', label: 'Auburn University' },
  { value: 'mississippi', label: 'University of Mississippi' },
  { value: 'mississippi-state', label: 'Mississippi State University' },
  { value: 'lsu', label: 'Louisiana State University' },
  { value: 'tulane', label: 'Tulane University' },
  { value: 'arkansas', label: 'University of Arkansas' },
  { value: 'oklahoma', label: 'University of Oklahoma' },
  { value: 'oklahoma-state', label: 'Oklahoma State University' },
  { value: 'kansas', label: 'University of Kansas' },
  { value: 'kansas-state', label: 'Kansas State University' },
  { value: 'wichita-state', label: 'Wichita State University' },
  { value: 'nebraska', label: 'University of Nebraska' },
  { value: 'north-dakota', label: 'University of North Dakota' },
  { value: 'south-dakota', label: 'University of South Dakota' },
  { value: 'montana', label: 'University of Montana' },
  { value: 'montana-state', label: 'Montana State University' },
  { value: 'wyoming', label: 'University of Wyoming' },
  { value: 'idaho', label: 'University of Idaho' },
  { value: 'boise-state', label: 'Boise State University' },
  { value: 'new-mexico', label: 'University of New Mexico' },
  { value: 'new-mexico-state', label: 'New Mexico State University' },
  { value: 'tennessee', label: 'University of Tennessee' },
  { value: 'vanderbilt-tn', label: 'Vanderbilt University' },
  { value: 'kentucky', label: 'University of Kentucky' },
  { value: 'louisville', label: 'University of Louisville' },
  { value: 'west-virginia', label: 'West Virginia University' },
  { value: 'marshall', label: 'Marshall University' },
  { value: 'delaware', label: 'University of Delaware' },
  { value: 'vermont', label: 'University of Vermont' },
  { value: 'maine', label: 'University of Maine' },
  { value: 'new-hampshire', label: 'University of New Hampshire' },
  { value: 'rhode-island', label: 'University of Rhode Island' },
  { value: 'connecticut', label: 'University of Connecticut' },
  { value: 'yale-ct', label: 'Yale University' },
  { value: 'wesleyan', label: 'Wesleyan University' },
  { value: 'trinity-ct', label: 'Trinity College' },
  { value: 'quinnipiac', label: 'Quinnipiac University' },
  { value: 'fairfield', label: 'Fairfield University' },
  { value: 'sacred-heart', label: 'Sacred Heart University' },
  { value: 'central-ct', label: 'Central Connecticut State University' },
  { value: 'eastern-ct', label: 'Eastern Connecticut State University' },
  { value: 'southern-ct', label: 'Southern Connecticut State University' },
  { value: 'western-ct', label: 'Western Connecticut State University' },
  { value: 'ccsu', label: 'Central Connecticut State University' },
  { value: 'ecsu', label: 'Eastern Connecticut State University' },
  { value: 'scsu', label: 'Southern Connecticut State University' },
  { value: 'wcsu', label: 'Western Connecticut State University' },
  // Add more schools as needed - this is a sample list
  // You may want to load this from your database instead
]

// Sort alphabetically by label
US_SCHOOLS.sort((a, b) => a.label.localeCompare(b.label))

